# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_wishlist_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='isPublic',
            new_name='is_public',
        ),
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
