# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170717_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
