# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170720_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Wishlist'),
        ),
    ]
